version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_PASSWORD: root
    volumes:
      - ./upload/uploads.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    restart: always
    ports:
      - 8585:80
    networks:
      - mysql
networks:
  mysql:
    external: true
